name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm ci
          npm run build
        env:
          VITE_EMAILJS_SECRET: ${{ vars.VITE_EMAILJS_SECRET  }}
          VITE_EMAILJS_SERVICE: ${{ vars.VITE_EMAILJS_SERVICE  }}
          VITE_EMAILJS_TEMPLATE: ${{ vars.VITE_EMAILJS_TEMPLATE  }}
          VITE_NESTOR_API: ${{ vars.VITE_NESTOR_API  }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: dist